server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/products/**

        - id: order-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/orders/**


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


